---

- hosts: junos
  gather_facts: false
  tasks:
    - name: VERSION  INFO
      cli_command:
        command: show version
     
      vars:
        ansible_connection: network_cli
      register: out
      ignore_errors: yes
    - debug: 
        msg: "{{ out.stdout_lines }}"

    - name: VERSION  INFO
      cli_command:
        command: show route 0.0.0.0

      vars:
        ansible_connection: network_cli
      register: out2
      ignore_errors: yes
    - debug: 
        msg: "{{ out2.stdout_lines }}"

