---
- name: Getting Post changes outputs from Juniper nodes
  hosts: junos
  gather_facts: false
  vars_prompt:
    - name: "show_cmd"
      prompt: "what cmd you want to run"
      private: no
  
  roles: 
    - tshoot-jun

